services:
  backend:
    build: .
    container_name: imdb-backend
    volumes:
      - "/home/arash/Desktop/my_volume/static:/project/static"
      - "/home/arash/Desktop/my_volume/media:/project/media"
      - "/home/arash/Desktop/my_volume/logs:/project/logs"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    command: sh -c "python manage.py migrate && 
                    python manage.py collectstatic --no-input && 
                    gunicorn -c gunicorn.conf.py"

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - "/home/arash/Desktop/my_volume/static:/project/static"
      - "/home/arash/Desktop/my_volume/media:/project/media"
    ports:
      - 80:80
    depends_on:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6380:6379
