# Generated by Django 4.1.2 on 2022-12-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(max_length=4)),
                ('currency_to', models.CharField(max_length=4)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
