# Generated by Django 4.1.2 on 2022-11-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(related_name='movies', through='movies.MovieCrew', to='movies.crew'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='movies.genre'),
        ),
    ]
