# Generated by Django 4.1.2 on 2022-12-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_crewcomment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Is Valid'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Time'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
